### ISSUE TITLE
Code file name conflict when using conda python environment.

### ISSUE THREAD

**Issue by nitesh31mishra** [agupta15k/ncsu_se_fall22_22#9]
**Branch - feature/akash-1** #2 
Facing the code file issue while running the test_main.py file. The conda python interpreter is accessing its own code.py file instead of accessing the local code folder and main file (`code/main.py`). Just renaming the folder will make it work most probably.

Below is the snapshot
![image](https://user-images.githubusercontent.com/54522260/187318730-d1e86f57-d4b3-4e9a-bf52-6486a750fee0.png)

**Comment by agupta15k** [comment]
Updated the directory structure to use `src` instead of `code`. Please use the steps mentioned in the readme file and see if the issue persists. Thanks

**Comment by nitesh31mishra** [comment]
Working fine now. Closing the issue.
